### ISSUE TITLE
Add card dynamically

### ISSUE THREAD

**Issue by chinajuanbob** [ravelinx22/react-swipeable-cards#1]
Hi, Is this component support adding cards dynamically, e.g when swipe the frond one, request data and add a new one in the bottom? thanks a lot!

**Comment by ravelinx22** [comment]
Hi, you can achieve that by saving your Card component array in your state and then simply adding new cards to that state like the following.

```JSX
 this.setState({
        cards: [...this.state.cards, newCard]
 });`
